### ISSUE TITLE
Lost and cannot edit saved rules

### ISSUE THREAD

**Issue by pistolilla** [bhughes339/vscode-replacerules#1]
After last update I can't see my previously saved rules nor I can edit or locate the json file.
Command "Replace rules: Edit rule" disappeared as well.

**Comment by bhughes339** [comment]
I recently updated the extension to use a json object in the main settings file as opposed to the separate json file.

You should be able to find your replacerules.json file in your home folder, which varies depending on which platform you're using, which you can copy and paste into the main settings file. Check the latest readme for the new settings format.

**Comment by pistolilla** [comment]
I can't find my old replacerules.json file. Any idea where could it be in macOS?

**Comment by bhughes339** [comment]
It should be located here:
~/Library/Application Support/Code/User/replacerules.json

I just checked my Macbook with the latest version of the extension and the json file is there.

**Comment by pistolilla** [comment]
God Thanks!!!!
