### ISSUE TITLE
[new feature] Apply all rules

### ISSUE THREAD

**Issue by FreHu** [bhughes339/vscode-replacerules#10]
I would like to specify a set of rules and apply all of them at once. This way, I would be able to make a makeshift code beautifier.

An even better feature would be to specify that a rule belongs to a ruleset, then run a particular ruleset.

**Comment by tnesavich** [comment]
The best way I am seeing to apply multiple rules at once is to put them into an array.  I have pasted an example of my config showing the merging of 3 rules into one below:

{
    "replacerules.rules": [
    {
      "name": "Ec2 Find / Replace (All)",   // This does all the find and relpace in one
      "find": [".*\sec2-",".us.*","-"],             // Notice the arrays []
      "replace": ["","","."],
    }, 
//    {
        "name": "Ec2 Find / Replace1",
        "find": ".*\sec2-",
        "replace": ""
      },
//    {
        "name": "Ec2 Find / Replace2",
        "find": ".us.*",
        "replace": ""
    },
//    {
        "name": "Ec2 Find / Replace3",
        "find": "-",
        "replace": "."
    } 
  ]
}

**Comment by ldexterldesign** [comment]
NO REPLY NECESSARY

Hi @FreHu,

@tnesavich is correct, this works for me in my user settings:

```json
{
  "replacerules.rules": [
    {
      "name": "All",
      "find": ["https://", "/ ", "/$", "www.", "\n\n+"],
      "replace": ["http://", " ", "", "", "\n"]
    },
    {
      "name": "Replace https with http",
      "find": "https://",
      "replace": "http://"
    },
    {
      "name": "Remove slash - non-trailing",
      "find": "/ ",
      "replace": " "
    },
    {
      "name": "Remove slash - trailing",
      "find": "/$",
      "replace": ""
    },
    {
      "name": "Remove www.",
      "find": "www.",
      "replace": ""
    },
    {
      "name": "Remove whitespace - empty line",
      "find": "\n\n+",
      "replace": "\n"
    }
  ]
}

```

The ability to reference (other) object values from within objects would be useful, so we can have a single source of truth, but I don't think this is possible in JSON - someone correct me if I'm wrong

Hope this is clear/useful

Regards

**Comment by bhughes339** [comment]
I'll be adding a "ruleset" feature to the next version which will allow you to run a specific set of rules.

**Comment by bhughes339** [comment]
This should be resolved in version 0.2.0. Let me know if there are any issues with the new functionality. Thank you!

**Comment by ldexterldesign** [comment]
Hi @bhughes339,

Hope you're well

Thanks for maintaining this mighty extension - I use it every day!

Thought I'd clean up my config today and saw your new ruleSets feature 💅, but unfortunately it's not working for me

Screencast: https://drive.google.com/open?id=1uql4C3hJGS4znh6bZcAqVo4bNZdGvnYr

```
{
    "editor.renderWhitespace": "all",
    "replacerules.ruleSets": {
        "whitespace - all": {
            "rules": [
                "whitespace - lines > []",
                "whitespace - characters - trailing > []"
            ]
        }
    },
    "replacerules.rules": {
        "[/] in quote > []": {
            "find": "/(?=\")",
            "replace": ""
        },
        "[/] non-trailing > []": {
            "find": "/",
            "replace": ""
        },
        "[/] trailing > []": {
            "find": "/$",
            "replace": ""
        },
        "[://] > [://www.]": {
            "find": "://(?!www.)",
            "replace": "://www."
        },
        "[://www.] > []": {
            "find": "://www.",
            "replace": "://"
        },
        "[http] > [https]": {
            "find": "http://",
            "replace": "https://"
        },
        "[https] > [http]": {
            "find": "https://",
            "replace": "http://"
        },
        "foo": {
            "find": "foo",
            "replace": "bar"
        },
        "whitespace - characters - trailing > []": {
            "find": " *$",
            "replace": ""
        },
        "whitespace - lines > []": {
            "find": "^\n",
            "replace": ""
        }
    }
}

```

Any thoughts?

If you have any issues (e.g. questions/queries) then happy to help

Yours hopefully

**Comment by bhughes339** [comment]
Hi @ldexterldesign, looks like I made a typo in the README, the settings key should actually be replacerules.rulesets (lowercase "s"). Sorry about that, and thanks for the report! I'll have the README fixed ASAP.
