### ISSUE TITLE
Configured rules do not do anything

### ISSUE THREAD

**Issue by chrischain** [bhughes339/vscode-replacerules#11]
The rules I've saved don't seem to do anything at all when I run them.

I've configured the rules in my settings.json per the example, and I see them in the menu when I go to run the rules, but nothing happens when I run them.  There are no errors in my settings.json.

I'm on Windows 7 Professional, Replace Rules 0.1.7, VSC 1.29.0 (user setup)

**Comment by bhughes339** [comment]
I made several changes to the extension and settings format, so I will close this issue. Please open up a new one if you're still having this issue.

**Comment by Michiel-Celis** [comment]
Hi bhughes339, noob here, i'm trying to add rules in package.json under "replacerules.rules".
But they do not show up in the cmd+alt+R menu
Could you add an example rule & ruleset to the package ?

I'm adding your example rule in README.MD in several places in package.json , i'm lost.

**Comment by bhughes339** [comment]
@Michiel-celis-code There is a full example in the README which should work. Can you post your settings.json file?

**Comment by webdesignmx05** [comment]
I had the same experience...the rules are non-responsive

**Comment by bhughes339** [comment]
@webdesignmx05 Please provide your settings.json file, it is not helpful to just comment "not working" without an example.

**Comment by chrischain** [comment]
It seems to be working fine for me... my settings.json syntax is pretty much identical to the example. I suggest anyone having difficulty take another look at the readme.md

**Comment by webdesignmx05** [comment]
@bhughes339 I got it to work for the 'Remove trailing and leading whitespace' rule. I'm not sure what happened earlier...it might have been missing comma between the rules or I just didn't see the contextual menu with the 'Remove trailing and leading whitespace' but now i'm curious as to why 'Remove blank lines' does not show in the CTRL+SHIFT+P  Replace Rules: Run Rule  contextual menu like 'Remove trailing and leading whitespace'. For this html example attached, when running either of the key bindings (ctrl+shift+/   or ctrl+shift+]) it performs the same result. Why, I thought only the one ran should execute? 

[10-18-2019.zip](https://github.com/bhughes339/vscode-replacerules/files/3745857/10-18-2019.zip)

**Comment by webdesignmx05** [comment]
Ahh...I found the answer...the removal of the languages constraint for "typescript" solved the issue. Thanks. 

    "Remove blank lines": {
            "find": "^\\n",
            "replace": ""
        },
