### ISSUE TITLE
Arguments missing with keybinding

### ISSUE THREAD

**Issue by joseika** [bhughes339/vscode-replacerules#14]
Hi,
I installed the Replace Rules extension today, just what I needed. 
But I have trouble with the arguments when using keybinding, it/they don't seem to be passed on from registerTextEditorCommand. 
I'm on Linux x64 4.15.0-47-generic, VSCode 1.33.0, Replace Rules 0.2.3.
Have not used the extension in previous versions of VSCode, so don't know if this is related to the latest release.

Got it to work by replacing in extension.js:
`
context.subscriptions.push(vscode.commands.registerTextEditorCommand('replacerules.runRuleSet', (textEditor, edit, args) => {
        let ruleSet = args['ruleSet'];
        new editProvider_1.default(textEditor).runRuleSet(ruleSet);
        return;
    }));
`

Also looking forward to the 'replace in workspace' feature from pull requests!

Thanks

**Comment by bhughes339** [comment]
I'll be pushing out a version that fixes this issue late today. Thank you!

**Comment by joseika** [comment]
Thank you for the prompt fix @bhughes339. Happy to confirm that my ruleset + keybinding works now.
