### ISSUE TITLE
rulesets vs ruleSets inconsistency

### ISSUE THREAD

**Issue by bhughes339** [bhughes339/vscode-replacerules#15]
I'm realizing there's a lot of inconsistency within the code (and forward-facing objects such as configuration keys) regarding the naming convention of rulesets. I believe "ruleset" should be treated as one word, so any references to "ruleSet" should be changed accordingly

**Comment by balazser** [comment]
In the documentation ```ruleSets``` is used instead of ```rulesets``` for the examples.
