### ISSUE TITLE
20+ rules ruleset

### ISSUE THREAD

**Issue by craigwann** [bhughes339/vscode-replacerules#16]
I'm using I have a ruleset with a little over 20 rules in it. All the rules work individually, but when I put them all into one ruleset the last 3-4 rules don't get applied to the entire file(the last 10% of the lines of the file the rules don't get applied). I've been able to get it to work if I break it into 3 rulesets.

**Comment by bhughes339** [comment]
Hi @craigwann, can you please provide your replacerules configuration objects so I can look into this. Thank you.

**Comment by craigwann** [comment]
[settings.zip](https://github.com/bhughes339/vscode-replacerules/files/3258379/settings.zip)
Thanks for looking into this!

**Comment by bhughes339** [comment]
@craigwann Thanks! Sorry, should have requested this before, but could you also provide a text file that you expect the issue to be reproduced with, which will match each of the rules in your settings? Thank you!

**Comment by craigwann** [comment]
[blu_lists_05312019.zip](https://github.com/bhughes339/vscode-replacerules/files/3259097/blu_lists_05312019.zip)
Hey @bhughes339,
Within the .ZIP is a short XML file. It's just a short sample XML that I use to template out what changes I'll make to the big XML data-dump. If you run the ruleset "list orig" you'll notice towards the end of the file that the "Replace <end> with </li>" rule quits running, at least that's what originally caught my eye. Again, THANKS!

**Comment by craigwann** [comment]
I just noticed that it stripped out the tags... the rule I noticed was the "Replace end with /li" which should be the last tag in the li tagged lists.

**Comment by bhughes339** [comment]
@craigwann I just pushed 0.2.7 onto the marketplace, which should resolve this issue. Please reopen this issue if any problems persist. Thanks!

**Comment by craigwann** [comment]
You are awesome! Thank you so much!

**Comment by craigwann** [comment]
So...I'm still having an issue with it. I've highlighted areas in a screenshot. 
![replacerules](https://user-images.githubusercontent.com/37252688/58997225-777a2c00-87b0-11e9-9704-968443fcbc70.jpg)

**Comment by bhughes339** [comment]
@craigwann Hmm, I'm not getting the same result as the screenshot, and I'm using the exact settings/xml file you provided. I see you're updated to 0.2.7...a few things to check:
1. Did you restart VSCode after updating?
2. Did you change any of the rules themselves?
3. Do you have any text selected prior to running the ruleset?

![image](https://user-images.githubusercontent.com/16418739/58997746-047eae80-87cc-11e9-814f-71282018da84.png)

**Comment by craigwann** [comment]
It was number 1...I didn't reload VSCode...again, thanks! I truly appreciate all the work you put into this!
