### ISSUE TITLE
Replace blank spaces

### ISSUE THREAD

**Issue by LeninZapata** [bhughes339/vscode-replacerules#17]
Hello, I want to replace the blank spaces the string in `_` but to put this rule what I get is that the selected string disappears and only appears a `_`, what am I doing wrong? 
```
    "replacerules.rules": {
        "Replace white space with sub-script": {
            "find": "/\\s+/",
            "replace": "_"
        }
    },
    "replacerules.rulesets": {
        "Remove lots of stuff": {
            "rules": [
                "Replace white space with sub-script",
            ]
        }
    }
```

**Comment by bhughes339** [comment]
Hi @LeninZapata, you don't need to enclose the "find" string with slashes, so use this instead:
`"find": "\\s+",`

**Comment by LeninZapata** [comment]
It worked! thank you.
You can also add another expression to lower the letters, that is HELLO to hello? How would it be ?

**Comment by bhughes339** [comment]
I do not think that is possible with regex, but there is a built-in function in VSCode that will do that called "Transform to Lowercase"
