### ISSUE TITLE
Object description in package.json

### ISSUE THREAD

**Issue by rioj7** [bhughes339/vscode-replacerules#19]
A few remarks regarding the object description in `package.json` for `replacerules.rules` and `replacerules.rulesets`.

* property "/" is not described in the README.md file
* the regex for `"patternProperties"` is `"^(.+)+$"`. The second `+` is not needed and makes the regex match more complex than needed.

**Comment by bhughes339** [comment]
Thanks. I believe I copied that JSON schema from an example on the official JSON schema site, so I assumed "properties" was required and that regex was correct. I'll make the changes.
