### ISSUE TITLE
No examples for escaping special characters in regex, or for literal option

### ISSUE THREAD

**Issue by ScottHutchinson** [bhughes339/vscode-replacerules#26]
I'm just trying to replace this literal string `(Skip = "Remove to run test")`.

I really don't even need regex for this, so I eventually figured out how to make it working using the `literal` option.

But if I did need regex, I couldn't make it work, because I needed to use literal parentheses, double quotes, and an equals sign. A regex that works on [regexpal](https://www.regexpal.com/) does not work in the settings.json file. This is what I tried, but it didn't do anything:
```
    "replacerules.rules": {
        "Remove skips": {
            "find": "\(Skip \= \"Remove to run test\"\)",
            "replace": ""
        }
    }
```

**Comment by bhughes339** [comment]
The reason that rule doesn't work is because you need to escape your backslashes in the "find" key. I know, it sounds silly, but it's due to a feature of JSON strings which allow the use of backslash for control characters (and escaping double quotes). I'll consider adding mention of this in the readme. I've also been trying to figure out a way to input a regular expression and have VSCode automatically escape it as a JSON string, so maybe I'll start working on that again. Thanks!

```json
"replacerules.rules": {
    "Remove skips": {
        "find": "\\(Skip = \"Remove to run test\"\\)",
        "replace": ""
    }
}
```

**Comment by ScottHutchinson** [comment]
That works. I don't have much experience with JSON, as you can tell. I don't understand why I have to escape the backslash that escapes the parenthesis, but not the backslash that escapes the double quote. Also I thought I needed to escape the equal sign, but apparently not. A few more examples would help a lot. Thanks!

**Comment by cparker4486** [comment]
@ScottHutchinson There are a few things happening in the working example which make it a little more difficult to understand.

First, the regex pattern is being stored in JSON which means strings should be wrapped in `"` double quotes. This means that any `"` _inside_ the JSON string must be escaped or the JS engine will terminate the string prematurely and cause an error.

Second, some characters in regex are special and must themselves be escaped. `"` is not one of them but `(` and `)` are.

Third, JavaScript is processing the regex pattern string before sending it to the regex engine. This is why you need two backslashes in some cases and one in others.

When we write the pattern it looks like this:

`"\\(Skip = \"Remove to run test\"\\)"`

Once JS has finished parsing it we end up with this:

`\(Skip = "Remove to run test"\)`

And that's what you want to send to the regex engine.

To be more specific, JavaScript consumed one layer of escape characters and sent the remainder of the string to the regex engine.

I hope that is helpful.

**Comment by bhughes339** [comment]
I added a new feature "Stringify regular expression" in version 0.4.1 that should help with JSON-formatting regex strings.
