### ISSUE TITLE
How to create a new rule

### ISSUE THREAD

**Issue by fatherjack** [bhughes339/vscode-replacerules#27]
How do I create a new rule? Would be good if there is a help example of how to create a new rule and a new rule set rather than executing or altering an existing rule.

**Comment by bhughes339** [comment]
Hi, you add a new rule by adding the replacerule.rules object from the README into settings.json (from the Command Palette: **Preferences: Open Settings (JSON)**). I haven't updated the instructions since the new VSCode Settings UI was introduced, so I'll look into updating it. Thanks!
