### ISSUE TITLE
I'm new to Visual Studio Code, How Do I Configure This Plugin?

### ISSUE THREAD

**Issue by wadsworj** [bhughes339/vscode-replacerules#38]
I'm new to Visual Studio Code.

There doesn't seem to be any direction in the readme about how to configure this plugin.

The "replacerules.rules" dictionary is mentioned multiple times, but nowhere does it mention where these rules are located?

Could someone let me (a newbie) know where I can find these rules? Are they in settings? in a file?

I have no idea.

**Comment by wadsworj** [comment]
Okay, I see that this issue was raised here before:

https://github.com/bhughes339/vscode-replacerules/issues/27

Now I can edit the rules.

I really think this basic step should be added to the readme though, assuming people have used Visual Studio Code before using this plugin would be a mistake (I'm trying to switch to Visual Studio Code as my text editor for essentially just this feature, so I have zero experience in Visual Studio Code)

**Comment by wadsworj** [comment]
I also see that there is an open pull request fixing this issue, can we get that pull request completed?

https://github.com/bhughes339/vscode-replacerules/pull/21

**Comment by bhughes339** [comment]
Yup, I missed that basic step in the Getting Started section. I merged #21 to hopefully make it more clear. Thank you!
