### ISSUE TITLE
Feature suggestion: Top and Tail

### ISSUE THREAD

**Issue by denzfox** [bhughes339/vscode-replacerules#39]
This extension is amazingly useful, thank you so much for making it. My suggestion is a simple one - when running a rule or a set it would be great to be able to specify a prefix and a suffix to put on the start/end of the output. I often find myself needing to replace not only a delimiter within a repeating pattern but also adjust the start and end of the entire string.

**Comment by bhughes339** [comment]
You should be able to do this with a multi-step rule. Say you wanted to replace commas with pipes and add a head/tail to each string:

```json
"Head/Tail Example": {
  "find": [
    ",",
    "(.+)"
  ],
  "replace": [
    "|",
    "<head>$1<tail>"
  ]
}
```

**Comment by denzfox** [comment]
You Billy are a genius - it works perfectly! I'm not very good with regex
so I don't understand *how* it works, but it definitely does. Thanks a
million :)

**Comment by bhughes339** [comment]
You're welcome, happy to help!
