### ISSUE TITLE
[bug] The cursor moves laterally when applying rules

### ISSUE THREAD

**Issue by atnbueno** [bhughes339/vscode-replacerules#4]
I've noticed some lateral movement of the cursor when applying some rules. For example, with these rules:
```
"replacerules.rules": [
    {
        "name": "OpenSCAD typos",
        "find": [
            "\\bcentre(\\s*=)",
            "(linear_extrude.+\\b)h(\\s*=.+)"
        ],
        "replace": [
            "center$1",
            "$1height$2"
        ]
    }
]
```
if applied to this text:
```
linear_extrude(centre = true, convexity = 10, twist = -500, h = 10)
    cylinder(r1=9.5, r2=19.5, centre=true, h=15);
```
and when the cursor is after any of the two ".5"

**Comment by atnbueno** [comment]
Next-day clarification:
I've noticed that the cursor doesn't "move" if you measure it from the beginning of the file, but if characters are added or removed, the cursor "moves" when measured from column 0.

**Comment by bhughes339** [comment]
Thanks for reporting! This issue should be fixed for the next release.
