### ISSUE TITLE
Can't seem to replace escaped characters with the non-escaped versions

### ISSUE THREAD

**Issue by Neighborkid01** [bhughes339/vscode-replacerules#40]
I am trying to convert HTML and JSON data between the raw multi-line text and a string to be stored in a database.
I commonly have to change '\"' into just '"' and "\n" into an actual new-line.
I can successfully change a double quote into an escaped double quote, and the same goes for new-lines, but it doesn't work the other way around.
So if I have a one-line string, I can't use this to auto expand the string like I do with my 2 regex replacements I normally do.

Ex.
```
"<p style=\"margin: auto;\">some text</p>\n<p style=\"height: auto;\">more text</p>"
```

Should become
```
<p style="margin: auto;">some text</p>
<p style="height: auto;">more text</p>
```

**Comment by bhughes339** [comment]
Slash escaping can be a bit obtuse with regex and JSON strings. This rule should work for your example:

```json
"Issue 40": {
    "find": [
        "\\\\\"",
        "\\\\n"
    ],
    "replace": [
        "\"",
        "\n"
    ]
}
```
