### ISSUE TITLE
Is there a way to change the case during replacement?

### ISSUE THREAD

**Issue by luizbgomide** [bhughes339/vscode-replacerules#41]
VS Code already has support for changing case using the `\l \u \L \U` flags with the `$n` , but I couldn't get it to work with Replace Rules.

Is there a way to do it? If not that could be a very good feature request.

**Comment by Kenobi-the-2nd** [comment]
I agree. I have found myself needing this capability on multiple occasions. It would come in very handy.

**Comment by bhughes339** [comment]
I don't believe extensions can hook into VSCode's find/replace logic, only the Javascript implementation. I'll look through the docs and see if there's anything relevant, but I doubt this will be possible unless the feature is added to TypeScript.

Relevant patch notes where the feature was added: https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_47.md#case-changing-in-regex-replace
