### ISSUE TITLE
JSON input with escape char

### ISSUE THREAD

**Issue by AnilCh26** [bhughes339/vscode-replacerules#42]

**Comment by bhughes339** [comment]
Hi, please provide an example of your issue. Thanks!

**Comment by AnilCh26** [comment]
Hi,
my Settings.Json has rule like below: where the replace string contains escape char's (it was exported from different system in as JSON file)
 "Replace path":  {
                                                               "find":  "#{LogPath}",
                                                               "replace":  "D:\\\\NTApps\\\\logstash\\\\abc-prod-v7.9.3\\\\logs"
                                                           },

Expectation:
After i run Replace rules with the above settings, Remove the escape char
some thing like this : "D:\\NTApps\\logstash\\abc-prod-v7.9.3\\logs"
