### ISSUE TITLE
ToLowercase \\L$1\\E or toUppercase \\U$1\\E

### ISSUE THREAD

**Issue by chris2fr** [bhughes339/vscode-replacerules#49]
Situaiton:

```
        "RuleOne": {
            "find":"^(.*)",$
            "replace": "\\L$1\\E"
        }
```
Current Result:

This produces the line with a litteral \L and \E in the line. 

Desired Result:

The line in lowercase.

See also

https://www.regular-expressions.info/refreplacecase.html

**Comment by bhughes339** [comment]
Hi,

Case-transformation tokens aren't supported in Javascript RegEx, so it can't be easily implemented. VSCode itself has support for case-changing in their find/replace, so if I find a way to hook into that, it could be possible. Otherwise, it's beyond the scope of the project.

**Comment by chrischain** [comment]
I realize this is closed and you've already stated that it is out of scope, but I just wanted to let you know that I would like to see a case-conversion feature implemented in some way as well.

I saw a hack suggested for a similar utility that implemented case changing in an interesting way: https://github.com/angelo-mollame/batch-replacer/issues/11

Perhaps that could lend some insight?
