### ISSUE TITLE
[Question] Line Deletion For Lines with More than "X" Characters

### ISSUE THREAD

**Issue by ThisNekoGuy** [bhughes339/vscode-replacerules#50]
I was considering trying this extension for a task I need done where I need lines from a document removed if that line exceeds 8 characters...

Is this possible? If so, could I be shown? (Would probably be a nice addition to add to the default functions, as well, if not already.)

**Comment by bhughes339** [comment]
Yes this is possible with regex:

```json
"find": "^.{9,}\\n?",
"replace": ""
```

This will remove all lines over 8 characters long. You can remove the `\\n?` part if you want to leave a blank line in place of the removed line.
