### ISSUE TITLE
[Feature Request] Option to disable screen updating

### ISSUE THREAD

**Issue by RichardJJG** [bhughes339/vscode-replacerules#52]
Hi, Bill,

Thanks very much creating this extension.

Might it be possible to add an option for disabling screen updating?
I ask because it takes a while for the extension to run a large number of rules, and I suspect disabling screen updating would speed it up.
The `Application.ScreenUpdating` property in VBA exists for this reason: https://docs.microsoft.com/en-us/office/vba/api/excel.application.screenupdating

Maybe the same thing is possible here.

**Comment by bhughes339** [comment]
Hi Richard, I don't believe VSCode has an equivalent to `ScreenUpdating` in VBA. Unfortunately slowness is the nature of the beast for many VSCode features and extensions (try formatting a large JSON file, for example 😢 ) so unless significant inefficiencies are discovered in the source code for Replace Rules, there's not much that can be done. Sorry!

**Comment by RichardJJG** [comment]
Okay, @bhughes339, thank you for the quick and informative response.
