### ISSUE TITLE
[bug] selected text after replacement

### ISSUE THREAD

**Issue by atnbueno** [bhughes339/vscode-replacerules#6]
I've noticed that if the cursor is at the end of a line, and a replacement results in this line being longer, the extra length ends up selected. For example, with these rules:
```
"replacerules.rules": [
    {
        "name": "OpenSCAD typos",
        "find": [
            "\\bcentre(\\s*=)",
            "(linear_extrude.+\\b)h(\\s*=.+)"
        ],
        "replace": [
            "center$1",
            "$1height$2"
        ]
    }
]
```
if applied to this text:
```
linear_extrude(centre = true, convexity = 10, twist = -500, h = 10)
    cylinder(r1=9.5, r2=19.5, centre=true, h=15);
```
and when the cursor is after at the end of the first line (after "10)"), this happens:

![](http://www.mundoplus.tv/atnbueno/replacerules_selected-after-bug.gif)

**Comment by bhughes339** [comment]
Closing per #7
